name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: test
        run: npm test
